[build]
  base = "/"
  command = "npm ci && npm run build:netlify"
  publish = "dist"

[deploy]
  branch = "main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  values = [
    { key = "Cache-Control", value = "public, max-age=0, must-revalidate" },
    { key = "Strict-Transport-Security", value = "max-age=31536000; includeSubDomains; preload" }
  ]

[build.environment]
  NODE_VERSION = "18.17.0"

[functions]
  directory = ".netlify/functions-internal/server"
  node_bundler = "esbuild"

[functions.node]
  version = "18.17.0"
