[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"

[deploy]
  branch = "main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
