[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "webpack"

[functions.build]
  command = "npm run build"
  base = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"

[build.environment]
  NODE_VERSION = "18.17.0"

[build.settings]
  base = "/"
  publish = ".output/public"

[headers]
  for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
