[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"

[deploy]
  branch = "main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build.environment]
  NUXT_PUBLIC_APOLLO_HTTP_ENDPOINT = "http://localhost:8000/api/kaiser/graphql"
  NUXT_PUBLIC_APOLLO_WS_ENDPOINT = "ws://localhost:8000/api/kaiser/graphql"
  NUXT_PUBLIC_HASURA_ADMIN_SECRET = "votre_hasura_admin_secret"  # Remplacer par votre secret Hasura réel
