[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
