// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09/05/2025 13:18:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/bomberkiller/Desktop/monsite/todo-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/plugins/**/*.{js,ts,mjs}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/composables/**/*.{js,ts,mjs}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/utils/**/*.{js,ts,mjs}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bomberkiller/Desktop/monsite/todo-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;